arquivo = open('arquivo.txt', 'a')
arquivo.write('Eu te amo, Iris\n')
arquivo.write('Eu te amo vagabunda, Iris\n')
arquivo.write('Eu te amo puta, Iris\n')
arquivo.write('Eu te amo meu amorzinho, Iris\n')
arquivo.write('Eu te amo caralho, Iris\n')
arquivo.write('Eu te amo cacete, Iris\n')
arquivo.write('Eu te amo pingola, Iris\n')
arquivo.write('Eu te amo ain, Iris\n')
arquivo.write('Eu te amo uiui, Iris\n')
arquivo.write('Eu te amo baby, Iris\n')
arquivo.write('Eu te amo muito, Iris\n')
arquivo.close()

leitura = open('arquivo.txt', 'r')
print(leitura.read())
leitura.close()